kelvininc/ui-components

packages/ui-components/src/components/switch-button/test/switch-button.e2e.ts
packages/ui-components/src/components/switch-button/test/switch-button.spec.tsx
packages/ui-components/stencil.config.ts

Add missing watchers tests to the `kv-switch-button` component to improve coverage.

test(switch-button): add missing watchers tests

---

packages/ui-components/src/components/link/link.scss

removes the default anchor tag underline and only shows it when hovering

fix(kv-link): fix anchor tag styling

---

packages/react-ui-components/package.json

Currently when adding the react `@kelvininc/react-ui-components` dependency to a project we get the error:
```
code EINVALIDTAGNAME
Invalid tag name ">=^17.0.2": Tags may not have any characters that encodeURIComponent encodes.
````
This PR fixes it by fixing the dependency notation.

chore(package.json): fix react dependency notation

---

packages/react-ui-components/src/stories/Components/SwitchButton.stories.tsx
packages/ui-components/src/components/switch-button/readme.md
packages/ui-components/src/components/switch-button/switch-button.scss
packages/ui-components/src/components/switch-button/switch-button.tsx
packages/ui-components/src/components/switch-button/switch-button.types.tsx
packages/ui-components/src/components/switch-button/test/__snapshots__/switch-button.spec.tsx.snap
packages/ui-components/src/components/switch-button/test/switch-button.e2e.ts
packages/ui-components/src/components/switch-button/test/switch-button.spec.tsx

This PR removes redundant states from the switch button component, such as the `isDisabled` as `isON` states.
It also renames the `state` string prop to a `checked` boolean prop in order to be easier to set from the parent component.

fix(switch-button): refactor component props and state

---

packages/ui-components/src/components/svg-icon/readme.md
packages/ui-components/src/components/svg-icon/svg-icon.tsx
packages/ui-components/src/components/svg-icon/test/__snapshots__/svg-icon.spec.tsx.snap
packages/ui-components/src/components/svg-icon/test/svg-icon.e2e.ts

Currently, the links to the SVG icons are relative to the page, which implies the SVG icons file to be served on every relative page where it's running.
This PR enables this public assets URL to be configured via prop and also defaults it to be absolute.

feat(svg-icon): enable public assets url configuration

---

packages/ui-components/src/components/tab-list/tab-list.scss

This overflow property was adding an scrollbar that was not possible to remove in maps

fix: remove overflow from tab navigation

---

packages/ui-components/src/components/action-button/action-button.scss

This PR should fix this misalignment on our action buttons:
Actual alignment:
After PR merge alignment:

fix(ui-components): fix action buttons border

---

packages/react-ui-components/src/stories/Components/MultiSelectDropdown.stories.tsx
packages/react-ui-components/src/stories/Components/SingleSelectDropdown.stories.tsx
packages/ui-components/src/components/dropdown-group/dropdown-group.config.ts
packages/ui-components/src/components/dropdown-group/dropdown-group.helper.ts
packages/ui-components/src/components/dropdown-group/dropdown-group.scss
packages/ui-components/src/components/dropdown-group/dropdown-group.tsx
packages/ui-components/src/components/dropdown-group/dropdown-group.types.ts
packages/ui-components/src/components/dropdown-group/readme.md
packages/ui-components/src/components/dropdown-group/usage/angular.md
packages/ui-components/src/components/dropdown-group/usage/react.md
packages/ui-components/src/components/multi-select-dropdown/multi-select-dropdown.helper.ts
packages/ui-components/src/components/multi-select-dropdown/multi-select-dropdown.scss
packages/ui-components/src/components/multi-select-dropdown/multi-select-dropdown.tsx
packages/ui-components/src/components/multi-select-dropdown/multi-select-dropdown.types.ts
packages/ui-components/src/components/multi-select-dropdown/readme.md
packages/ui-components/src/components/select-option/readme.md
packages/ui-components/src/components/select-option/select-option.scss
packages/ui-components/src/components/select/readme.md
packages/ui-components/src/components/select/select.scss
packages/ui-components/src/components/single-select-dropdown/readme.md
packages/ui-components/src/components/single-select-dropdown/single-select-dropdown.scss
packages/ui-components/src/components/single-select-dropdown/single-select-dropdown.tsx
packages/ui-components/src/components/single-select-dropdown/single-select-dropdown.types.ts

Now dropdown options can be grouped by a name.
**Screenshots**

feat(dropdown-group)!: add options groups to dropdown single and multi select

---

packages/ui-components/src/components/dropdown/dropdown.tsx

When clicking outside this dropdown wouldn't close, I was trying to figure out the problem and realized that the console was giving this error.
Digging deeper, I figured out that this error was actually the dropdown problem. So I made some modifications to the function, and it seems to be working. My only doubt  is the type of the target (it was suggested by VSCode).

fix(dropdown): fix check for click outside fuction

---

packages/ui-components/src/components/dropdown/dropdown.tsx

When the dropdown selector doesn't have space to expand to the right, it will expand to the right.
When it doesn't have space to the left, it will expand to the right.
The same happens if the selector doesn't have space at the bottom.
f.png)

fix(dropdown): Add fallbackPlacements

---

packages/angular-ui-components/.scripts/copy-assets.js
packages/angular-ui-components/README.md
packages/react-ui-components/.scripts/copy-icons.js
packages/react-ui-components/README.md

Even thought the timestamp was added with the best intentions of being able to see the most recent file on top when listing the public directory, that does not work because every time we deploy we get a new file and our users have to reload the file because its name changed.

fix(icon): remove timestamp from copied SVG of symbols [KMAPS-385]

---

packages/react-ui-components/src/stories/Components/TextField.stories.tsx
packages/ui-components/src/components/text-field/text-field.config.ts

Removes placeholder added by the input mask and fixed some stories that had misused templates

fix(text-field): remove placeholder 0 on type numeric on hover or focus

---

packages/ui-components/src/components/range/range.helper.ts
packages/ui-components/src/components/range/range.tsx

This PR changes the value of the offset applied to the number on top of the range slider. 
This is particularly needed when the range is used inside a modal and the width of the slider is almost the same width of the modal. If the number displayed has at least 4 characters, the number will overflow the space available.
Another approach to consider would be adding a flag to enable/disable this offset but i will leave this question open to the review.

fix(range): add offset to the input value

---

packages/react-ui-components/src/stories/Components/Tree.stories.tsx
packages/react-ui-components/src/stories/Components/TreeDropdown.stories.tsx
packages/ui-components/src/components/tooltip/readme.md
packages/ui-components/src/components/tooltip/test/__snapshots__/tooltip.spec.tsx.snap
packages/ui-components/src/components/tooltip/tooltip.scss
packages/ui-components/src/components/tooltip/tooltip.tsx
packages/ui-components/src/components/tree-dropdown/readme.md
packages/ui-components/src/components/tree-dropdown/tree-dropdown.tsx
packages/ui-components/src/components/tree-item/readme.md
packages/ui-components/src/components/tree-item/test/__snapshots__/tree-item.spec.tsx.snap
packages/ui-components/src/components/tree-item/tree-item.tsx
packages/ui-components/src/components/tree/readme.md
packages/ui-components/src/components/tree/tree.tsx

When hovering a label :point_up:

feat(tree-dropdown): add tooltip to label [KMAPS-522,KMAPS-523]

---

packages/ui-components/src/components/tooltip/tooltip.tsx

`child` should be inferred as `HTMLElement | null` because `private getContentElement = (): HTMLElement | null`

fix(tooltip): check if child is null before `removeEventListeners` [KMAPS-532]

---

packages/ui-components/src/components/text-field/text-field.config.ts
packages/ui-components/src/components/text-field/text-field.tsx

This PR removes the placeholder from the inputmask configuration because this was causing the input to display only the first letter of the placeholder. The placeholder should only be defined in the input html tag

fix(textfield): remove placeholder from inputmask configuration

---

packages/ui-components/src/components/tooltip/test/__snapshots__/tooltip.spec.tsx.snap
packages/ui-components/src/components/tooltip/tooltip.config.ts
packages/ui-components/src/components/tooltip/tooltip.tsx

So, I talked with Iza to understand if this was a maps only requirement or a library requirement and she confirmed me that it was a library requirement.

feat(tooltip): add default delay to tooltip

---

packages/ui-components/src/components/tooltip/readme.md
packages/ui-components/src/components/tooltip/tooltip.scss
packages/ui-components/src/components/tree-item/readme.md

I added this style so the white space does not get set by a CSS class in a inner div. What was happening in some cases was that a inner div a style such as `white-space: nowrap;` and the usage of the tooltip component was not producing the desired results (with the tooltip text leaving the card).

fix(tooltip): add white space normal

---

packages/react-ui-components/src/stories/foundation/Introduction/Introduction.stories.mdx

docs: bump on introduction page documentation

---

packages/react-ui-components/src/components/SchemaForm/Templates/ArrayFieldTemplate/ArrayFieldTemplate.module.scss
packages/ui-components/src/components/action-button-icon/action-button-icon.scss

This PR fixes an height offset added to the kv-action-button-icon.
This is just a quick fix since the problem might be in one of the kv-action-button mixins that were developed with the kv-icon offset in height. However, a more deep research is needed to confirm that there is actual something wrong with one of the mixins.

fix(action-button-icon): remove height offset

---

packages/react-ui-components/package-lock.json
packages/react-ui-components/package.json
packages/react-ui-components/rollup.config.js
packages/react-ui-components/src/components/SchemaForm/SchemaForm.tsx
packages/react-ui-components/src/components/SchemaForm/Templates/ArrayFieldItemTemplate/ArrayFieldItemTemplate.tsx
packages/react-ui-components/src/components/SchemaForm/Templates/BaseInputTemplate/BaseInputTemplate.tsx
packages/react-ui-components/src/components/SchemaForm/Templates/DescriptionFieldTemplate/DescriptionFieldTemplate.tsx
packages/react-ui-components/src/components/SchemaForm/Templates/ErrorListTemplate/ErrorListTemplate.tsx
packages/react-ui-components/src/components/SchemaForm/Templates/FieldTemplate/FieldTemplate.tsx
packages/react-ui-components/src/components/SchemaForm/Templates/ObjectFieldTemplate/ObjectFieldTemplate.tsx
packages/react-ui-components/src/components/SchemaForm/Templates/TitleFieldTemplate/TitleFieldTemplate.tsx
packages/react-ui-components/src/components/SchemaForm/Templates/helper.ts
packages/react-ui-components/src/components/SchemaForm/Widgets/CheckboxesWidget/CheckboxesWidget.tsx
packages/react-ui-components/src/components/SchemaForm/Widgets/RadioWidget/RadioWidget.tsx
packages/react-ui-components/src/components/SchemaForm/Widgets/ReadOnlyValueWidget/ReadOnlyValueWidget.tsx
packages/react-ui-components/src/components/SchemaForm/Widgets/SelectWidget/SelectWidget.tsx
packages/react-ui-components/src/components/SchemaForm/Widgets/SelectWidget/utils.ts
packages/react-ui-components/src/utils/useScroll.ts

**Problem**
The `react-ui-components generate` a commonjs package that uses `lodash-es` as a module.
**Solution**
With [optimize lodash plugin](https://www.npmjs.com/package/@optimize-lodash/rollup-plugin) ES & CJS generated files have different approaches to handle lodash methods;
ES
`import { isEmpty } from 'lodash-es'`
CJS
`import isEmpty from lodash/isEmpty`

fix(react-ui-components): change build config to organize correctly the lodash dependency

---

packages/react-ui-components/src/stories/Components/Modal.stories.tsx
packages/ui-components/src/components/modal/modal.base.scss
packages/ui-components/src/components/modal/modal.light.scss
packages/ui-components/src/components/modal/modal.night.scss
packages/ui-components/src/components/modal/modal.tsx
packages/ui-components/src/components/modal/modal.types.ts
packages/ui-components/src/components/modal/readme.md
packages/ui-components/src/components/modal/test/modal.e2e.ts
packages/ui-components/src/components/modal/test/modal.spec.tsx

The modal component suffered from some logic issues that wouldn't allow us to define if we wanted a click outside to send a `close` event, this PR introduces a fix to define if we want that behaviour to occur or not.
This PR also introduces a smaller fix to the modal's z-index property so it can be properly rendered above any content, the value can be customised through a CSS prop.

fix(modal)!: click outside behavior can now be customized

---

packages/react-ui-components/src/components/CodeEditor/CodeEditor.tsx
packages/react-ui-components/src/components/CodeEditor/config.ts
packages/react-ui-components/src/components/CodeEditor/readme.md
packages/react-ui-components/src/components/CodeEditor/types.ts
packages/react-ui-components/src/stories/Components/CodeEditor.stories.tsx

This pull request adds the possibility of having a padding at the top of the editor, the screenshot may not be very clear but you can see the blank space at the top.
After scrolling down:

feat(code-editor): add padding top option

---

packages/react-ui-components/src/components/CodeEditor/CodeEditor.tsx
packages/react-ui-components/src/components/CodeEditor/config.ts
packages/react-ui-components/src/components/CodeEditor/readme.md
packages/react-ui-components/src/components/CodeEditor/types.ts
packages/react-ui-components/src/stories/Components/CodeEditor.stories.tsx

BREAKING CHANGE: This commit removes the `debounceTime` property from the component, therefore removing the default 200ms wait before firing a change event.
Removing this also removed the memoization of the onChange callback, which was causing some issues in render cycles.

fix(code-editor)!: remove debounce time from onChange

---

packages/ui-components/src/components/select/select.scss
packages/ui-components/src/components/tooltip/readme.md

**Description**
Adds a 12px padding to the top and the bottom of the options list.
**Demo**

feat(dropdown-base): add top and bottom spacing

---

packages/ui-components/src/components/advanced-date-select-dropdown/advanced-date-select-dropdown.config.ts
packages/ui-components/src/components/calendar-advanced-date-selector/calendar-advanced-date-selector.scss
packages/ui-components/src/components/dropdown/dropdown.config.ts

This PR adds the flip middleware to the `kv-dropdown` that was removed on #240.
It also adds a fixed width to the calendar dropdown in order to allow it to have an absolute position.

fix(dropdown): add missing flip middleware

---

packages/ui-components/src/components/form-help-text/form-help-text.scss
packages/ui-components/src/components/text-field/text-field.base.scss

The help text component had the incorrect color set for it's label, this PR fixes it so it matches our design system.

fix(help-text): change help-text label color to match DS

---

packages/react-ui-components/src/components/CodeEditor/CodeEditor.tsx
packages/react-ui-components/src/components/CodeEditor/config.ts
packages/react-ui-components/src/components/CodeEditor/readme.md
packages/react-ui-components/src/components/CodeEditor/types.ts
packages/react-ui-components/src/components/CodeEditor/utils.ts
packages/react-ui-components/src/stories/Components/CodeEditor.stories.tsx
packages/react-ui-components/src/utils/useFontsApi/constants.ts
packages/react-ui-components/src/utils/useFontsApi/index.ts
packages/react-ui-components/src/utils/useFontsApi/types.ts
packages/react-ui-components/src/utils/useFontsApi/useFontsApi.ts

BREAKING CHANGE: `readOnly` and `paddingTop` properties were moved to the `customOptions` object

refactor(code-editor)!: separate font loading logic and add kelvin theme

---

packages/react-ui-components/src/stories/foundation/Typography/Typography.scss
packages/react-ui-components/src/stories/foundation/Typography/Typography.stories.mdx
packages/ui-components/src/assets/styles/kv-typography.scss

This PR updates the typography mixins according to our DS.
**BREAKING CHANGE**: `kv-font-h3-regular` and `kv-font-label-medium-light` mixins were removed.

fix(typography)!: update typography mixins according to DS

---

packages/react-ui-components/src/stories/Components/AbsoluteTimePicker.stories.tsx
packages/react-ui-components/src/stories/Components/DateTimeInput.stories.tsx
packages/react-ui-components/src/stories/Components/TimePicker.stories.tsx
packages/ui-components/src/components/time-picker/readme.md
packages/ui-components/src/components/time-picker/time-picker.tsx
packages/ui-components/src/components/time-picker/time-picker.types.ts

There was a bug when the show calendar toggle was set to true and the component was opened for the first time. The time picker view didnt match with the toggle state.
It was also added an event that emits the state of the toggle when it changes.

fix(time-picker): sync initial view with show calendar toggle state

---

packages/ui-components/src/components/relative-time-picker/relative-time-picker.config.ts
packages/ui-components/src/components/relative-time-picker/relative-time-picker.helper.ts
packages/ui-components/src/components/relative-time-picker/relative-time-picker.tsx
packages/ui-components/src/components/relative-time-picker/relative-time-picker.types.ts
packages/ui-components/src/utils/date.helper.ts

In firefox, the list of relative time options was not appearing because for some reason, no timezone was being considered in the method that created the date even though we were sending it via props. 
This PR adresses the issue and also adds a format to the dates that are used in the config for us to be able to specify the format of the date that we sent in the config file.

fix(relative-time-picker): add default timezone to avoid firefox erros on relative time options list

---

packages/react-ui-components/src/stories/Components/TimePicker.stories.tsx
packages/ui-components/src/components/time-picker/time-picker.tsx

This pr fixes an issue that happened when a timeOption was defined but the timezone was undefined. This would result in an error. 
With this, we can discard the timezone and the component will assume the browser default.

fix(time-picker): allow empty timezone state in props

---

packages/ui-components/src/components/action-button-split/readme.md
packages/ui-components/src/components/action-button/action-button.scss
packages/ui-components/src/components/action-button/action-button.tsx
packages/ui-components/src/components/action-button/test/__snapshots__/action-button.spec.ts.snap

Removes the padding that was added to the action button component due to the loading animation PR. This code its not needed and should be removed.

fix(action-button): remove padding around button due to loading animation

---

packages/ui-components/src/components/action-button/action-button.scss

We're having an issue with the ghost action button. When the cursor was on over the button after the animation ended the button does a little jump. The following video illustrates the issue:
https://github.com/kelvininc/ui-components/assets/17494742/86397a73-0407-440d-95c7-7d50c8b3e3ce

fix(action-button): remove ghost button flickering on hover

---

packages/react-ui-components/src/stories/Components/TimePicker.stories.tsx
packages/ui-components/src/components/relative-time-picker/relative-time-picker.config.ts

This PR re-orders the default time picker options and fixes the show calendar toggle in the stories that needed to have a state to handle the changes.

feat(relative-time-picker): reorder items in relative time picker default config

---

packages/react-ui-components/src/stories/Components/Wizard.stories.tsx
packages/ui-components/src/components/wizard-footer/readme.md
packages/ui-components/src/components/wizard-footer/test/__snapshots__/wizard-footer.spec.tsx.snap
packages/ui-components/src/components/wizard-footer/wizard-footer.tsx
packages/ui-components/src/components/wizard-footer/wizard-footer.types.ts
packages/ui-components/src/components/wizard/readme.md
packages/ui-components/src/components/wizard/test/__snapshots__/wizard.spec.tsx.snap
packages/ui-components/src/components/wizard/test/wizard.mock.ts
packages/ui-components/src/components/wizard/test/wizard.spec.tsx
packages/ui-components/src/components/wizard/wizard.helper.ts
packages/ui-components/src/components/wizard/wizard.tsx
packages/ui-components/src/components/wizard/wizard.types.ts

I noticed that in some situations we need to allow the user to stop a wizard flow at any step.
We could use the `additional-actions` slot and control this from outside this component, but I believe this behaviour will be needed in more scenarios shortly hence we might as well add it to the Component itself.
That's what this PR does, adds a cancelable prop to the IWizardStep to allow any step to have a "cancel" action button.

feat(wizard): add a more imperative approach to footer actions

---

packages/ui-components/src/components/wizard-footer/readme.md
packages/ui-components/src/components/wizard-footer/test/__snapshots__/wizard-footer.spec.tsx.snap
packages/ui-components/src/components/wizard-footer/wizard-footer.scss
packages/ui-components/src/components/wizard-footer/wizard-footer.tsx
packages/ui-components/src/components/wizard/test/__snapshots__/wizard.spec.tsx.snap
packages/ui-components/src/components/wizard/wizard.tsx

feat(wizard-footer): move additional actions slot for added flexibility

---

packages/ui-components/src/components/modal/modal.base.scss

fix(modal): add ellipsis to title when width is fixed to prevent overflow

---

packages/ui-components/src/illustrations/illustrations.scss

We were having an additional height on the illustrations that was being added by the generated components. This was causing the illustration to add an additional 4px aprox to the specified size we were defining with the custom css props.

fix(illustrations): remove added height from illustrations

---

packages/ui-components/src/components/time-picker/time-picker.helper.ts
packages/ui-components/src/components/time-picker/time-picker.tsx

When we set the time and we dont send the timezone, the time picker should assume the local default timezone.

fix(timepicker): add default timezone as fallback

---

packages/ui-components/src/components/relative-time-picker/relative-time-picker.tsx

The search input was being hidden when the user searched for values and the number of items was less than the minimum search values.

fix(relative-time-picker): keep timezone search input visible when user searches for values

---

packages/ui-components/src/components/form-help-text/form-help-text.scss

fix(form-help-text): text wrapping under the icon

---

packages/ui-components/src/components/absolute-time-picker-dropdown-input/absolute-time-picker-dropdown-input.tsx
packages/ui-components/src/components/absolute-time-picker-dropdown-input/absolute-time-picker-dropdown-input.utils.ts

This PR changes the behaviour of the component to handle the case where a user sets an input and closes the dropdown, and after that, he opens again and cleans the input. If the time was previously set, we should fill the input again with that value. 
The value of the input only changes when the user sets a new valid time or when it picks a new day in the calendar.

fix(absolute-time-picker-input): reset input text when user closes dropdown with empty input

---

packages/ui-components/src/components/single-select-dropdown/single-select-dropdown.tsx

The watch methods are running before `componentWillLoad` when the tab isn't active resulting in an error when `calculateLabelValue` is called.

fix(select-multi-options): prevent potential undefined error in selectOptions access

---

packages/react-ui-components/src/components/ToasterContainer/config.ts
packages/react-ui-components/src/components/ToasterContainer/index.tsx
packages/ui-components/src/components/badge/readme.md
packages/ui-components/src/components/calendar-day/readme.md
packages/ui-components/src/components/calendar/readme.md
packages/ui-components/src/components/form-label/readme.md
packages/ui-components/src/components/info-label/readme.md
packages/ui-components/src/components/modal/readme.md
packages/ui-components/src/components/radio/readme.md
packages/ui-components/src/components/range/readme.md
packages/ui-components/src/components/text-field/readme.md
packages/ui-components/src/components/toaster/toaster.tsx
packages/ui-components/src/components/tree-item/readme.md
packages/ui-components/src/components/tree/readme.md

When the toaster is open and a TTL appears that resets the value to `0` and after a moment appears another data, the toaster doesn't use the default TTL.

fix(toaster): watch ttl changes to clear and start new timeout

---

packages/ui-components/src/components/absolute-time-picker-dropdown-input/absolute-time-picker-dropdown-input.tsx
packages/ui-components/src/components/date-time-input/date-time-input.scss
packages/ui-components/src/components/info-label/info-label.tsx
packages/ui-components/src/components/info-label/readme.md
packages/ui-components/src/components/toggle-button-group/readme.md
packages/ui-components/src/components/toggle-button-group/toggle-button-group.tsx

This pr changes the behaviour of the calendar.
- When the user selects a date, the selected input shifts to the other input if  the input is empty.
- Setting same from and to date when the user clicks in a date which is not valid, for example if he selects a "from" date after the "to" date.
This pr also adds missing documentation that was emitting some warnings in the console.

fix(absolute-time-picker-input): change input focus when user selects a date

---

packages/ui-components/src/components/dropdown-base/dropdown-base.tsx

This pr changes the event that can close the dropdown. Using a click, the event listener will only respond to mouse left clicks. Using mousedown will respond to both left and right.

fix(dropdown): replace click event listener by mousedown

---

apps/react-storybook/src/components/data-display/description-list/DescriptionList.module.scss
apps/react-storybook/src/components/data-display/description-list/DescriptionList.stories.tsx
packages/ui-components/src/components/copy-to-clipboard/readme.md
packages/ui-components/src/components/description-list/description-list.scss
packages/ui-components/src/components/description-list/description-list.tsx
packages/ui-components/src/components/description-list/description-list.types.ts
packages/ui-components/src/components/description-list/readme.md
packages/ui-components/src/components/description-list/test/__snapshots__/description-list.spec.tsx.snap

- added subgrid row option to enable style costumization (eg: border-bottom)
- integrated kv-copy-to-clipboard component

feat(description-list): enable component to be more customizable
