package-lock.json, packages/angular-ui-components/src/component-library.module.ts, packages/angular-ui-components/src/generated/component.ts, packages/angular-ui-components/src/generated/text-value-accessor.ts, packages/angular-ui-components/src/generated/value-accessor.ts, packages/react-ui-components/src/components/index.ts, packages/react-ui-components/src/components/stencil-generated/index.ts, packages/react-ui-components/src/stories/Components/ActionButton.stories.tsx, packages/react-ui-components/src/stories/Components/SwitchButton.stories.tsx, packages/ui-components/.stylelintrc, packages/ui-components/package.json, packages/ui-components/src/components.d.ts, packages/ui-components/src/components/switch-button/readme.md, packages/ui-components/src/components/switch-button/switch-button.scss, packages/ui-components/src/components/switch-button/switch-button.tsx, packages/ui-components/src/components/switch-button/switch-button.types.tsx, packages/ui-components/src/components/switch-button/test/__snapshots__/switch-button.spec.tsx.snap, packages/ui-components/src/components/switch-button/test/switch-button.e2e.ts, packages/ui-components/src/components/switch-button/test/switch-button.spec.tsx, packages/ui-components/src/components/switch-button/usage/angular.md, packages/ui-components/src/components/switch-button/usage/javascript.md, packages/ui-components/src/components/switch-button/usage/react.md, packages/ui-components/src/components/switch-button/usage/stencil.md, packages/ui-components/src/types.ts, packages/ui-components/stencil.config.ts
=> feat(switch-button): add component

.github/workflows/publish-master.yml, packages/react-ui-components/package.json
=> fix: include assets in react build

packages/angular-ui-components/src/kv-ui-components.module.ts, packages/react-ui-components/src/stories/Components/RadioButton.stories.tsx, packages/ui-components/src/components/breadcrumb-list/test/breadcrumb-list.spec.tsx, packages/ui-components/src/components/radio-button/radio-button.scss, packages/ui-components/src/components/radio-button/radio-button.tsx, packages/ui-components/src/components/radio-button/readme.md, packages/ui-components/src/components/radio-button/test/__snapshots__/radio-button.spec.tsx.snap, packages/ui-components/src/components/radio-button/test/radio-button.e2e.ts, packages/ui-components/src/components/radio-button/test/radio-button.spec.tsx, packages/ui-components/src/components/radio-button/usage/angular.md, packages/ui-components/src/components/radio-button/usage/react.md
=> feat(radio-button): add radio button component

packages/angular-ui-components/src/kv-ui-components.module.ts, packages/react-ui-components/src/stories/Components/TagLetter.stories.tsx, packages/ui-components/src/components/tag-letter/readme.md, packages/ui-components/src/components/tag-letter/tag-letter.scss, packages/ui-components/src/components/tag-letter/tag-letter.tsx, packages/ui-components/src/components/tag-letter/test/__snapshots__/tag-letter.spec.tsx.snap, packages/ui-components/src/components/tag-letter/test/tag-letter.e2e.ts, packages/ui-components/src/components/tag-letter/test/tag-letter.spec.tsx, packages/ui-components/src/components/tag-letter/usage/angular.md, packages/ui-components/src/components/tag-letter/usage/react.md
=> feat(kv-tag-letter): migrate tag letter component

packages/react-ui-components/.storybook/preview.js, packages/react-ui-components/src/stories/Components/ActionButton.stories.tsx, packages/react-ui-components/src/stories/Components/Breadcrumb.stories.tsx, packages/react-ui-components/src/stories/Components/BreadcrumbItem.stories.tsx, packages/react-ui-components/src/stories/Components/BreadcrumbList.stories.tsx, packages/react-ui-components/src/stories/Components/Link.stories.tsx, packages/react-ui-components/src/stories/Components/Loader.stories.tsx, packages/react-ui-components/src/stories/Components/RadioButton.stories.tsx, packages/react-ui-components/src/stories/Components/StateIndicator.stories.tsx, packages/react-ui-components/src/stories/Components/SvgIcon.stories.tsx, packages/react-ui-components/src/stories/Components/SwitchButton.stories.tsx, packages/react-ui-components/src/stories/Components/TabItem.stories.tsx, packages/react-ui-components/src/stories/Components/TabList.stories.tsx, packages/react-ui-components/src/stories/Components/TabNavigation.stories.tsx, packages/react-ui-components/src/stories/Components/TagLetter.stories.tsx
Improves storybook organization
=> chore(storybook): improve storybook folder organization

packages/react-ui-components/src/stories/Components/ActionButton.stories.tsx, packages/react-ui-components/src/stories/Components/ActionButtonIcon.stories.tsx, packages/react-ui-components/src/stories/Components/ActionButtonSplit.stories.tsx, packages/react-ui-components/src/stories/Components/ActionButtonText.stories.tsx, packages/ui-components/src/components/action-button-icon/action-button-icon.scss, packages/ui-components/src/components/action-button-icon/readme.md, packages/ui-components/src/components/action-button-split/action-button-split.scss, packages/ui-components/src/components/action-button-split/readme.md
=> fix(storybook): fix action button story names

packages/angular-ui-components/src/kv-ui-components.module.ts, packages/react-ui-components/src/stories/Components/SummaryCard.stories.tsx, packages/ui-components/src/components/summary-card/readme.md, packages/ui-components/src/components/summary-card/summary-card.base.scss, packages/ui-components/src/components/summary-card/summary-card.light.scss, packages/ui-components/src/components/summary-card/summary-card.night.scss, packages/ui-components/src/components/summary-card/summary-card.tsx, packages/ui-components/src/components/summary-card/summary-card.types.ts, packages/ui-components/src/components/summary-card/test/__snapshots__/summary-card.spec.tsx.snap, packages/ui-components/src/components/summary-card/test/summary-card.e2e.ts, packages/ui-components/src/components/summary-card/test/summary-card.spec.tsx, packages/ui-components/src/components/summary-card/usage/angular.md, packages/ui-components/src/components/summary-card/usage/react.md, packages/ui-components/src/types.ts
>![image](https://user-images.githubusercontent.com/13225555/158667808-703607fe-fc04-4300-9231-58f30fc84a6c.png)
>![image](https://user-images.githubusercontent.com/13225555/158667878-d29f4870-e203-4161-9441-83a2d561f0b8.png)
=> feat(summary-card): add summary card component

packages/angular-ui-components/src/controllers/index.ts, packages/angular-ui-components/src/controllers/toaster/toaster-controller.component.ts, packages/angular-ui-components/src/controllers/toaster/toaster-controller.module.ts, packages/angular-ui-components/src/controllers/toaster/toaster-controller.service.ts, packages/angular-ui-components/src/kv-ui-components.module.ts, packages/angular-ui-components/src/public-api.ts, packages/react-ui-components/src/components/controllers/toaster-controller.tsx, packages/react-ui-components/src/components/controllers/toaster-controller.types.ts, packages/react-ui-components/src/stories/Components/Toaster.stories.tsx, packages/ui-components/src/components/icon/readme.md, packages/ui-components/src/components/toaster/readme.md, packages/ui-components/src/components/toaster/test/__snapshots__/toaster.spec.tsx.snap, packages/ui-components/src/components/toaster/test/toaster.e2e.ts, packages/ui-components/src/components/toaster/test/toaster.spec.tsx, packages/ui-components/src/components/toaster/toaster.config.ts, packages/ui-components/src/components/toaster/toaster.scss, packages/ui-components/src/components/toaster/toaster.tsx, packages/ui-components/src/components/toaster/toaster.types.ts, packages/ui-components/src/components/toaster/usage/angular.md, packages/ui-components/src/components/toaster/usage/react.md, packages/ui-components/src/index.html, packages/ui-components/src/types.ts
Please check:
-  Angular and React controllers added
- Should close state be inside toaster component with a prop watch to update the internal state
=> feat: toaster component

packages/angular-ui-components/src/kv-ui-components.module.ts, packages/react-ui-components/src/stories/Components/RadioButton.stories.tsx, packages/react-ui-components/src/stories/Components/RadioButtonGroup.stories.tsx, packages/ui-components/src/components/radio-button-group/radio-button-group.scss, packages/ui-components/src/components/radio-button-group/radio-button-group.tsx, packages/ui-components/src/components/radio-button-group/readme.md, packages/ui-components/src/components/radio-button-group/test/__snapshots__/tab-navigation.spec.tsx.snap, packages/ui-components/src/components/radio-button-group/test/radio-button-group.mock.ts, packages/ui-components/src/components/radio-button-group/test/tab-navigation.spec.tsx, packages/ui-components/src/components/radio-button/radio-button.scss, packages/ui-components/src/components/radio-button/radio-button.tsx, packages/ui-components/src/components/radio-button/radio-button.types.tsx, packages/ui-components/src/components/radio-button/readme.md, packages/ui-components/src/components/radio-button/test/__snapshots__/radio-button.spec.tsx.snap, packages/ui-components/src/components/radio-button/test/radio-button.e2e.ts, packages/ui-components/src/components/radio-button/test/radio-button.spec.tsx, packages/ui-components/src/components/radio-button/usage/angular.md, packages/ui-components/src/components/radio-button/usage/react.md, packages/ui-components/src/types.ts
…adio and create new components kv-radio-button and kv-radio-button-group
=> feat(kv-radio-button-group): create new components kv-radio-button and kv-radio-button-group

packages/angular-ui-components/src/kv-ui-components.module.ts, packages/react-ui-components/src/stories/Components/TreeItem.stories.tsx, packages/ui-components/package.json, packages/ui-components/readme.md, packages/ui-components/src/assets/styles/kv-mixins.scss, packages/ui-components/src/components/icon/readme.md, packages/ui-components/src/components/summary-card/summary-card.base.scss, packages/ui-components/src/components/tree-item/readme.md, packages/ui-components/src/components/tree-item/test/__snapshots__/tree-item.spec.tsx.snap, packages/ui-components/src/components/tree-item/test/tree-item.e2e.ts, packages/ui-components/src/components/tree-item/test/tree-item.spec.tsx, packages/ui-components/src/components/tree-item/tree-item.base.scss, packages/ui-components/src/components/tree-item/tree-item.config.ts, packages/ui-components/src/components/tree-item/tree-item.light.scss, packages/ui-components/src/components/tree-item/tree-item.night.scss, packages/ui-components/src/components/tree-item/tree-item.tsx, packages/ui-components/src/components/tree-item/tree-item.types.ts, packages/ui-components/src/components/tree-item/usage/angular.md, packages/ui-components/src/components/tree-item/usage/react.md, packages/ui-components/src/types.ts
**NIGHT MODE:**
>![image](https://user-images.githubusercontent.com/6940723/167672573-6240b444-4015-4c6e-a9a5-8cb95cdad43b.png)![image](https://user-images.githubusercontent.com/6940723/167672176-26d5c201-c1c7-4d5b-bc65-4e644c742fd5.png)
**LIGHT MODE:**
>![image](https://user-images.githubusercontent.com/6940723/167672388-dfb6f7f2-7ffd-4cad-8c97-6f34e725aaf2.png)![image](https://user-images.githubusercontent.com/6940723/167672285-d695654b-5d16-4789-9827-4047adbbd50d.png)
=> feat(tree-item): add tree item component

packages/angular-ui-components/src/kv-ui-components.module.ts, packages/react-ui-components/src/stories/Components/Tree.stories.tsx, packages/ui-components/.eslintrc.json, packages/ui-components/src/components/tree-item/readme.md, packages/ui-components/src/components/tree-item/tree-item.base.scss, packages/ui-components/src/components/tree-item/tree-item.tsx, packages/ui-components/src/components/tree/readme.md, packages/ui-components/src/components/tree/test/__snapshots__/tree.spec.tsx.snap, packages/ui-components/src/components/tree/test/tree.mock.ts, packages/ui-components/src/components/tree/test/tree.spec.tsx, packages/ui-components/src/components/tree/tree.scss, packages/ui-components/src/components/tree/tree.tsx, packages/ui-components/src/components/tree/tree.types.ts, packages/ui-components/src/components/tree/usage/angular.md, packages/ui-components/src/components/tree/usage/react.md, packages/ui-components/src/types.ts
**NIGHT MODE**
>![image](https://user-images.githubusercontent.com/6940723/168126012-04814774-73bd-43f4-a339-65d6ea6e46ae.png)
**LIGHT MODE**
>![image](https://user-images.githubusercontent.com/6940723/168125382-21282613-f517-4d1e-9aca-793d3a09238c.png)
=> feat(tree): add tree component

packages/ui-components/src/components/dropdown/dropdown.scss, packages/ui-components/src/components/dropdown/dropdown.tsx
Open dropdown list at the top if  there is no space available at the bottom
=> fix(kv-dropdown): open dropdown list at the top

packages/ui-components/src/components/action-button/action-button.scss
=> fix(ui-components): change box-sizing to border box to include the border size in the defined height

packages/angular-ui-components/src/kv-ui-components.module.ts, packages/react-ui-components/package-lock.json, packages/react-ui-components/src/components/ModalOverlay/config.ts, packages/react-ui-components/src/components/ModalOverlay/index.tsx, packages/react-ui-components/src/components/ModalOverlay/types.ts, packages/react-ui-components/src/components/index.ts, packages/react-ui-components/src/stories/Components/Modal.stories.tsx, packages/ui-components/src/components/icon/readme.md, packages/ui-components/src/components/modal/modal.base.scss, packages/ui-components/src/components/modal/modal.light.scss, packages/ui-components/src/components/modal/modal.night.scss, packages/ui-components/src/components/modal/modal.tsx, packages/ui-components/src/components/modal/modal.types.ts, packages/ui-components/src/components/modal/readme.md, packages/ui-components/src/components/modal/test/__snapshots__/modal.spec.tsx.snap, packages/ui-components/src/components/modal/test/modal.e2e.ts, packages/ui-components/src/components/modal/test/modal.spec.tsx, packages/ui-components/src/components/modal/usage/react.md, packages/ui-components/src/types.ts
=> feat(modal): add modal component

packages/react-ui-components/src/stories/Components/SelectOption.stories.tsx, packages/ui-components/src/components/select-option/readme.md, packages/ui-components/src/components/select-option/select-option.scss, packages/ui-components/src/components/select-option/select-option.tsx, packages/ui-components/src/components/select-option/select-option.types.ts, packages/ui-components/src/components/select-option/test/__snapshots__/select-option.spec.tsx.snap, packages/ui-components/src/components/select-option/test/select-option.e2e.ts, packages/ui-components/src/components/select-option/test/select-option.spec.tsx, packages/ui-components/src/components/select/readme.md, packages/ui-components/src/components/select/select.scss
=> feat(select-option): add bottom slot for content

packages/react-ui-components/src/stories/Components/TextField.stories.tsx, packages/ui-components/src/components/range-dates-select-dropdown/test/__snapshots__/range-dates-select-dropdown.spec.tsx.snap, packages/ui-components/src/components/text-field/readme.md, packages/ui-components/src/components/text-field/text-field.base.scss, packages/ui-components/src/components/text-field/text-field.tsx
=> feat(textfield): add left slot to enable currency text

packages/react-ui-components/src/stories/Components/Range.stories.tsx, packages/ui-components/src/components/range/range.helper.ts, packages/ui-components/src/components/range/range.scss, packages/ui-components/src/components/range/range.tsx, packages/ui-components/src/components/range/test/__snapshots__/range.spec.tsx.snap
I started this PR because the range wasn't working correctly in firefox. When you tried to move the slider by dragging the button it didn't work.
When trying to fix the problem, I realized that I could do a little refactor and simplify the component.
I tested in firefox & chrome and both were fine, tell me what you think and if I'm doing something wrong or if I can do something better.
=> refactor(range): Refactor range & fix range in firefox

packages/ui-components/src/assets/styles/kv-mixins.scss, packages/ui-components/src/components/select/select.scss
=> fix: add custom scroll to timezone select [KMAPS-454]

packages/react-ui-components/src/stories/Components/Tree.stories.tsx, packages/react-ui-components/src/stories/Components/TreeDropdown.stories.tsx, packages/ui-components/src/components/range-dates-select-dropdown/test/range-dates-select-dropdown.spec.tsx, packages/ui-components/src/components/tree-dropdown/readme.md, packages/ui-components/src/components/tree-dropdown/tree-dropdown.scss, packages/ui-components/src/components/tree-dropdown/tree-dropdown.tsx, packages/ui-components/src/components/tree-item/readme.md, packages/ui-components/src/components/tree-item/test/__snapshots__/tree-item.spec.tsx.snap, packages/ui-components/src/components/tree-item/tree-item.base.scss, packages/ui-components/src/components/tree-item/tree-item.tsx, packages/ui-components/src/components/tree/readme.md, packages/ui-components/src/components/tree/test/__snapshots__/tree.spec.tsx.snap, packages/ui-components/src/components/tree/tree.base.scss, packages/ui-components/src/components/tree/tree.light.scss, packages/ui-components/src/components/tree/tree.night.scss, packages/ui-components/src/components/tree/tree.tsx
| | |
|:-:|:-:|
| ![image](https://user-images.githubusercontent.com/19409687/191057814-229a4831-f472-45a2-bbcf-8cac0caf3106.png) | ![image](https://user-images.githubusercontent.com/19409687/191057987-6252a6e9-1eca-46e4-a32b-663a2cd2aa32.png) |
| ![image](https://user-images.githubusercontent.com/19409687/191058113-190e24c6-e432-4b49-adb9-1cdd2567a1ba.png) | ![image](https://user-images.githubusercontent.com/19409687/191058205-cd293ddf-e75f-4f60-ace6-75e26e975dc5.png) |
=> feat: add dropdown tree component [KMAPS-423]

packages/ui-components/src/components/dropdown-base/dropdown-base.scss
Reverts kelvininc/ui-components#157
=> Revert "fix(dropdown-base): Remove positions of dropdown-base"

packages/ui-components/src/components/range/range.base.scss, packages/ui-components/src/components/range/range.light.scss, packages/ui-components/src/components/range/range.night.scss, packages/ui-components/src/components/range/range.tsx, packages/ui-components/src/components/range/range.types.ts, packages/ui-components/src/components/range/readme.md
=> feat(range)!: adding customization properties

packages/react-ui-components/src/components/SchemaForm/FieldTemplate/FieldTemplate.module.scss, packages/react-ui-components/src/components/SchemaForm/SchemaForm.tsx, packages/react-ui-components/src/components/SchemaForm/Widgets/SelectWidget/SelectWidget.tsx, packages/react-ui-components/src/components/SchemaForm/Widgets/SelectWidget/types.ts, packages/react-ui-components/src/components/SchemaForm/Widgets/SelectWidget/utils.ts, packages/react-ui-components/src/stories/Components/SchemaForm.stories.tsx, packages/react-ui-components/src/stories/Components/helpers/dropdown.helper.ts, packages/ui-components/src/components/dropdown-base/dropdown-base.scss, packages/ui-components/src/components/single-select-dropdown/readme.md
This PR adds a few features and fixes some issues:
- feat: add searchable behaviour to the select widget
- feat: add clearable selection behaviour to the multi-select widget
- feat: enable a custom display value function
- feat: enable widget customization via custom CSS class
- fix: bind select widget value with form prop
- fix: set the dropdown height to 100%
=> feat(schema-form): add searchable behaviour to select widget

packages/react-ui-components/src/components/SchemaForm/Widgets/CheckboxesWidget/CheckboxesWidget.tsx, packages/react-ui-components/src/components/SchemaForm/Widgets/CheckboxesWidget/config.ts, packages/react-ui-components/src/components/SchemaForm/Widgets/CheckboxesWidget/index.ts, packages/react-ui-components/src/components/SchemaForm/Widgets/CheckboxesWidget/types.ts, packages/react-ui-components/src/components/SchemaForm/Widgets/CheckboxesWidget/utils.ts, packages/react-ui-components/src/components/SchemaForm/Widgets/Widgets.ts, packages/react-ui-components/src/stories/Components/SchemaForm.stories.tsx
=> feat(schema-form): add checkboxes widget

packages/react-ui-components/src/stories/Components/TagStatus.stories.tsx, packages/ui-components/src/components/icon/readme.md, packages/ui-components/src/components/tag-status/readme.md, packages/ui-components/src/components/tag-status/tag-status.config.ts, packages/ui-components/src/components/tag-status/tag-status.scss, packages/ui-components/src/components/tag-status/tag-status.tsx, packages/ui-components/src/components/tag-status/tag-status.types.ts, packages/ui-components/src/components/tag-status/test/__snapshots__/status.spec.tsx.snap, packages/ui-components/src/components/tag-status/test/status.e2e.ts, packages/ui-components/src/components/tag-status/test/status.spec.tsx, packages/ui-components/src/components/tag-status/usage/angular.md, packages/ui-components/src/components/tag-status/usage/react.md, packages/ui-components/src/types.ts
=> feat(status): add new status tag component

packages/ui-components/package-lock.json, packages/ui-components/package.json, packages/ui-components/stencil.config.ts
https://stenciljs.com/docs/config#sourcemap
https://github.com/danvk/source-map-explorer/blob/master/README.md#generating-source-maps
https://github.com/ionic-team/stencil/issues/1744
=> chore: add script to get ui-components bundle size

packages/react-ui-components/.storybook/main.js, packages/react-ui-components/.storybook/preview-head.html, packages/react-ui-components/package-lock.json, packages/react-ui-components/package.json, packages/react-ui-components/src/components/CodeEditor/CodeEditor.tsx, packages/react-ui-components/src/components/CodeEditor/config.ts, packages/react-ui-components/src/components/CodeEditor/index.ts, packages/react-ui-components/src/components/CodeEditor/readme.md, packages/react-ui-components/src/components/CodeEditor/types.ts, packages/react-ui-components/src/components/index.ts, packages/react-ui-components/src/stories/Components/CodeEditor.stories.tsx
=> feat(code-editor): add component

packages/angular-ui-components/src/kv-ui-components.module.ts, packages/react-ui-components/src/stories/Components/WizardHeader.stories.tsx, packages/ui-components/src/components/wizard-header/readme.md, packages/ui-components/src/components/wizard-header/test/__snapshots__/wizard-header.spec.tsx.snap, packages/ui-components/src/components/wizard-header/test/wizard-header.spec.tsx, packages/ui-components/src/components/wizard-header/usage/angular.md, packages/ui-components/src/components/wizard-header/usage/react.md, packages/ui-components/src/components/wizard-header/wizard-header.base.scss, packages/ui-components/src/components/wizard-header/wizard-header.night.scss, packages/ui-components/src/components/wizard-header/wizard-header.tsx, packages/ui-components/src/components/wizard-header/wizard-header.types.ts, packages/ui-components/src/types.ts
=> feat(wizard-header): add component

packages/ui-components/src/assets/styles/kv-theme.default.scss
Fixed a small misalignment between design colors and lib colors in calculated colors (light and dark). We decide make it static.
=> fix(colors): fix light/dark color codes

packages/angular-ui-components/src/kv-ui-components.module.ts, packages/react-ui-components/src/stories/Components/Wizard.stories.tsx, packages/ui-components/src/components/modal/modal.base.scss, packages/ui-components/src/components/wizard-footer/readme.md, packages/ui-components/src/components/wizard-header/readme.md, packages/ui-components/src/components/wizard/readme.md, packages/ui-components/src/components/wizard/test/__snapshots__/wizard.spec.tsx.snap, packages/ui-components/src/components/wizard/test/wizard.mock.ts, packages/ui-components/src/components/wizard/test/wizard.spec.tsx, packages/ui-components/src/components/wizard/usage/angular.md, packages/ui-components/src/components/wizard/usage/react.md, packages/ui-components/src/components/wizard/wizard.helper.ts, packages/ui-components/src/components/wizard/wizard.scss, packages/ui-components/src/components/wizard/wizard.tsx, packages/ui-components/src/components/wizard/wizard.types.ts, packages/ui-components/src/types.ts
>![image](https://user-images.githubusercontent.com/6940723/218613345-bb192a83-805f-4525-af3e-22fcd8dcce32.png)
>![image](https://user-images.githubusercontent.com/6940723/218613390-b1905696-f705-460c-8aae-e93874e2123e.png)
=> feat(wizard): add wizard component

packages/react-ui-components/src/components/SchemaForm/Widgets/SelectWidget/SelectWidget.tsx, packages/ui-components/src/components/select/select.scss, packages/ui-components/src/components/single-select-dropdown/readme.md, packages/ui-components/src/components/single-select-dropdown/single-select-dropdown.config.ts, packages/ui-components/src/components/single-select-dropdown/single-select-dropdown.tsx, packages/ui-components/src/components/single-select-dropdown/single-select-dropdown.types.ts
=> feat(single-select-dropdown): allow clear selected item in single-select-dropdown

packages/ui-components/src/components/action-button/action-button.scss
=> fix(action-button): remove unwanted right border [KMAPS-884]

packages/ui-components/src/components/dropdown/dropdown.tsx
Updates the `kv-single-select-dropdown ` component according to the design specs
Demo:
=> fix(single-select-dropdown): update icon size [KMAPS-910]

packages/react-ui-components/src/components/SchemaForm/SchemaForm.tsx, packages/react-ui-components/src/stories/Components/SchemaForm.stories.tsx
=> feat(schema-form): add tooltip props to submit button

packages/react-ui-components/src/stories/Components/Wizard.stories.tsx, packages/ui-components/src/components/icon/readme.md, packages/ui-components/src/components/toggle-tip/readme.md, packages/ui-components/src/components/tooltip-text/tooltip-text.scss, packages/ui-components/src/components/wizard-header/readme.md, packages/ui-components/src/components/wizard-header/wizard-header.scss, packages/ui-components/src/components/wizard-header/wizard-header.tsx, packages/ui-components/src/components/wizard-header/wizard-header.types.ts, packages/ui-components/src/components/wizard/readme.md, packages/ui-components/src/components/wizard/wizard.helper.ts, packages/ui-components/src/components/wizard/wizard.types.ts
=> feat(wizard): add a toggle-tip to the wizard header

packages/ui-components/src/components/text-area/text-area.tsx, packages/ui-components/src/components/text-field/text-field.tsx, packages/ui-components/src/utils/string.helper.ts
=> fix(text-input): count string length in UTF-8 instead UTF-16

packages/ui-components/src/components/alert/alert.tsx, packages/ui-components/src/components/alert/test/__snapshots__/kv-alert.spec.tsx.snap
=> feat(alert): add slot to description

packages/react-ui-components/src/components/SchemaForm/Fields/BooleanField/BooleanField.tsx, packages/react-ui-components/src/components/SchemaForm/Fields/BooleanField/config.ts, packages/react-ui-components/src/components/SchemaForm/Fields/BooleanField/utils.ts, packages/react-ui-components/src/stories/Components/SchemaForm.stories.tsx
=> feat(schema-form): add 'select' widget to boolean fields

packages/react-ui-components/src/components/SchemaForm/Fields/BooleanField/BooleanField.tsx, packages/react-ui-components/src/components/SchemaForm/Templates/FieldTemplate/FieldTemplate.tsx, packages/react-ui-components/src/components/SchemaForm/Templates/ObjectFieldTemplate/ObjectFieldTemplate.tsx, packages/react-ui-components/src/components/SchemaForm/Widgets/FileWidget/FileWidget.module.scss, packages/react-ui-components/src/components/SchemaForm/Widgets/FileWidget/FileWidget.tsx, packages/react-ui-components/src/components/SchemaForm/Widgets/FileWidget/index.ts, packages/react-ui-components/src/components/SchemaForm/Widgets/FileWidget/types.ts, packages/react-ui-components/src/components/SchemaForm/Widgets/FileWidget/utils.ts, packages/react-ui-components/src/components/SchemaForm/Widgets/RadioWidget/RadioWidget.module.scss, packages/react-ui-components/src/components/SchemaForm/Widgets/RadioWidget/RadioWidget.tsx, packages/react-ui-components/src/components/SchemaForm/Widgets/index.ts, packages/react-ui-components/src/stories/Components/SchemaForm.stories.tsx, packages/ui-components/src/components/radio-list/radio-list.tsx, packages/ui-components/src/components/radio/radio.base.scss
=> feat(schema-form): add file widget

packages/ui-components/package-lock.json, packages/ui-components/package.json, packages/ui-components/scripts/generate-illustrations.js, packages/ui-components/src/components/portal/portal.config.ts, packages/ui-components/src/components/toggle-tip/toggle-tip.config.ts, packages/ui-components/src/components/tooltip/tooltip.config.ts, packages/ui-components/src/utils/floating-ui.helper.ts
This PR bumps some of the packages used in our repo. I would suggest merging the bump-stencil branch PR to dev first and generate a build with that first since this PR might introduce some changes in our maps repo.
=> chore: bump dependencies packages

packages/react-ui-components/src/components/SchemaForm/Fields/BooleanField/BooleanField.tsx, packages/react-ui-components/src/components/SchemaForm/Fields/BooleanField/config.ts, packages/react-ui-components/src/components/SchemaForm/Fields/BooleanField/utils.ts, packages/react-ui-components/src/components/SchemaForm/Templates/ArrayFieldTemplate/ArrayFieldTemplate.tsx, packages/react-ui-components/src/components/SchemaForm/Templates/BaseInputTemplate/BaseInputTemplate.tsx, packages/react-ui-components/src/components/SchemaForm/Templates/FieldTemplate/FieldTemplate.module.scss, packages/react-ui-components/src/components/SchemaForm/Templates/FieldTemplate/FieldTemplate.tsx, packages/react-ui-components/src/components/SchemaForm/Templates/ObjectFieldTemplate/ObjectFieldTemplate.tsx, packages/react-ui-components/src/components/SchemaForm/Templates/TitleFieldTemplate/TitleFieldTemplate.module.scss, packages/react-ui-components/src/components/SchemaForm/Templates/TitleFieldTemplate/TitleFieldTemplate.tsx, packages/react-ui-components/src/components/SchemaForm/Widgets/CheckboxesWidget/CheckboxesWidget.tsx, packages/react-ui-components/src/components/SchemaForm/Widgets/RadioListWidget/RadioListWidget.module.scss, packages/react-ui-components/src/components/SchemaForm/Widgets/RadioListWidget/RadioListWidget.tsx, packages/react-ui-components/src/components/SchemaForm/Widgets/RadioListWidget/index.ts, packages/react-ui-components/src/components/SchemaForm/Widgets/SelectWidget/SelectWidget.tsx, packages/react-ui-components/src/components/SchemaForm/Widgets/TextareaWidget/TextareaWidget.tsx, packages/react-ui-components/src/components/SchemaForm/Widgets/index.ts, packages/react-ui-components/src/components/SchemaForm/types.ts, packages/ui-components/src/components/form-help-text/form-help-text.scss, packages/ui-components/src/components/range-dates-select-dropdown/test/__snapshots__/range-dates-select-dropdown.spec.tsx.snap, packages/ui-components/src/components/text-field/test/__snapshots__/text-field.spec.tsx.snap, packages/ui-components/src/components/text-field/text-field.tsx
=> feat(schema-form): add the radio list widget

packages/ui-components/src/components/icon/readme.md, packages/ui-components/src/components/step-bar/readme.md, packages/ui-components/src/components/step-bar/step-bar.scss, packages/ui-components/src/components/step-bar/step-bar.tsx, packages/ui-components/src/components/step-bar/test/__snapshots__/step-bar.spec.tsx.snap, packages/ui-components/src/components/step-indicator/readme.md, packages/ui-components/src/components/step-indicator/step-indicator.scss, packages/ui-components/src/components/step-indicator/step-indicator.tsx, packages/ui-components/src/components/step-indicator/test/__snapshots__/step-indicator.spec.tsx.snap, packages/ui-components/src/components/step-progress-bar/step-progress-bar.base.scss, packages/ui-components/src/components/step-progress-bar/step-progress-bar.tsx, packages/ui-components/src/components/step-progress-bar/test/__snapshots__/step-progress-bar.spec.tsx.snap, packages/ui-components/src/components/wizard-footer/readme.md, packages/ui-components/src/components/wizard-footer/wizard-footer.tsx, packages/ui-components/src/components/wizard-footer/wizard-footer.types.ts, packages/ui-components/src/components/wizard/readme.md, packages/ui-components/src/components/wizard/test/__snapshots__/wizard.spec.tsx.snap, packages/ui-components/src/components/wizard/test/wizard.spec.tsx, packages/ui-components/src/components/wizard/wizard.helper.ts
=> refactor(step-progress): align the step-progress with new designs

packages/react-ui-components/src/stories/Components/AbsoluteTimePickerDropdownInput.stories.tsx, packages/react-ui-components/src/stories/Components/DateTimeInput.stories.tsx, packages/ui-components/src/components/absolute-time-picker-dropdown-input/absolute-time-picker-dropdown-input.config.ts, packages/ui-components/src/components/absolute-time-picker-dropdown-input/absolute-time-picker-dropdown-input.scss, packages/ui-components/src/components/absolute-time-picker-dropdown-input/absolute-time-picker-dropdown-input.tsx, packages/ui-components/src/components/absolute-time-picker-dropdown-input/absolute-time-picker-dropdown-input.types.ts, packages/ui-components/src/components/absolute-time-picker-dropdown-input/absolute-time-picker-dropdown-input.utils.ts, packages/ui-components/src/components/absolute-time-picker-dropdown-input/readme.md, packages/ui-components/src/components/absolute-time-picker-dropdown-input/test/__snapshots__/absolute-time-picker-dropdown-input.spec.tsx.snap, packages/ui-components/src/components/absolute-time-picker-dropdown-input/test/absolute-time-picker-dropdown-input.e2e.ts, packages/ui-components/src/components/absolute-time-picker-dropdown-input/test/absolute-time-picker-dropdown-input.spec.tsx, packages/ui-components/src/components/absolute-time-picker-dropdown-input/usage/angular.md, packages/ui-components/src/components/absolute-time-picker-dropdown-input/usage/react.md, packages/ui-components/src/components/absolute-time-picker-dropdown/readme.md, packages/ui-components/src/components/absolute-time-picker/readme.md, packages/ui-components/src/components/date-time-input/date-time-input.config.ts, packages/ui-components/src/components/date-time-input/date-time-input.scss, packages/ui-components/src/components/date-time-input/date-time-input.tsx, packages/ui-components/src/components/date-time-input/date-time-input.types.ts, packages/ui-components/src/components/date-time-input/readme.md, packages/ui-components/src/components/date-time-input/test/__snapshots__/date-time-input.spec.tsx.snap, packages/ui-components/src/components/dropdown-base/readme.md, packages/ui-components/src/components/icon/icon.types.ts, packages/ui-components/src/components/icon/readme.md, packages/ui-components/src/components/time-picker-calendar/readme.md, packages/ui-components/src/components/time-picker-calendar/time-picker-calendar.tsx, packages/ui-components/src/components/time-picker-calendar/time-picker-calendar.types.ts, packages/ui-components/src/components/time-picker/readme.md, packages/ui-components/src/types.ts, packages/ui-components/src/utils/date.helper.ts
=> feat: add new input absolute time picker

packages/react-ui-components/src/components/SchemaForm/Fields/BooleanField/BooleanField.tsx, packages/react-ui-components/src/components/SchemaForm/Fields/BooleanField/utils.ts, packages/react-ui-components/src/components/SchemaForm/Templates/TitleFieldTemplate/TitleFieldTemplate.tsx, packages/react-ui-components/src/components/SchemaForm/Widgets/RadioListWidget/RadioListWidget.tsx, packages/ui-components/src/components/badge/readme.md, packages/ui-components/src/components/calendar-day/readme.md, packages/ui-components/src/components/calendar/readme.md, packages/ui-components/src/components/form-label/readme.md, packages/ui-components/src/components/info-label/info-label.tsx, packages/ui-components/src/components/info-label/readme.md, packages/ui-components/src/components/info-label/test/__snapshots__/info-label.spec.tsx.snap, packages/ui-components/src/components/modal/readme.md, packages/ui-components/src/components/radio/readme.md, packages/ui-components/src/components/range/readme.md, packages/ui-components/src/components/text-field/readme.md, packages/ui-components/src/components/tree-item/readme.md, packages/ui-components/src/components/tree/readme.md
allow customize field title and use a custom widget in boolean fields
=> feat(schema-form): allow customize field title and use a custom widget

packages/react-ui-components/src/stories/Components/InlineEditableField.stories.tsx, packages/ui-components/src/components/action-button-icon/readme.md, packages/ui-components/src/components/inline-editable-field/inline-editable-field.config.ts, packages/ui-components/src/components/inline-editable-field/inline-editable-field.scss, packages/ui-components/src/components/inline-editable-field/inline-editable-field.tsx, packages/ui-components/src/components/inline-editable-field/readme.md, packages/ui-components/src/components/inline-editable-field/test/inline-editable-field.e2e.ts, packages/ui-components/src/components/inline-editable-field/test/inline-editable-field.spec.tsx
=> feat(kv-inline-editable-field): adds component

apps/react-storybook/src/mocks/dropdown.mock.ts, packages/ui-components/src/components/absolute-time-picker-dropdown/absolute-time-picker-dropdown.tsx, packages/ui-components/src/components/absolute-time-picker-dropdown/absolute-time-picker-dropdown.types.ts, packages/ui-components/src/components/dropdown/dropdown.tsx, packages/ui-components/src/components/select-multi-options/select-multi-options.tsx, packages/ui-components/src/components/select-option/select-option.tsx, packages/ui-components/src/components/select-option/select-option.types.ts, packages/ui-components/src/components/single-select-dropdown/single-select-dropdown.tsx
- feat(select-option): adds a tooltip into icon and export icon part to be stylized outside
- feat(absolute-time-picker-dropdown): enables dropdown open state to be controlled externally
=> feat: adds some improvments on absolute calendar and select option

apps/react-storybook/src/components/inputs/toggle-button/ToggleButton.stories.tsx, apps/react-storybook/src/components/inputs/toggle-switch/ToggleSwitch.stories.tsx, packages/ui-components/src/components/toggle-button-group/readme.md, packages/ui-components/src/components/toggle-button-group/toggle-button-group.tsx, packages/ui-components/src/components/toggle-button/readme.md, packages/ui-components/src/components/toggle-button/test/__snapshots__/toggle-button.spec.tsx.snap, packages/ui-components/src/components/toggle-button/toggle-button.tsx, packages/ui-components/src/components/toggle-button/toggle-button.types.ts, packages/ui-components/src/components/toggle-switch/readme.md, packages/ui-components/src/components/toggle-switch/toggle-switch.tsx, packages/ui-components/src/components/tooltip/readme.md
Link to ticket: https://kelvininc.atlassian.net/browse/KFE-2416
=> feat(toggle-button): adds support to display tooltip text [KFE-2416]

packages/ui-components/src/utils/select.helper.ts
[KFE-2506]
[KFE-2506]: https://kelvininc.atlassian.net/browse/KFE-2506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(multi-select): fix select all to discard the disabled [KFE-2506]
